### ISSUE TITLE
是否有查询用户在线状态的接口

### ISSUE THREAD

**Issue by mpasdi** [anyRTC-UseCase/ARCallPlus#3]
我现在有个需求， 查询所有在线用户，请问有相关的接口吗。或者说能查询单个用户状态的接口。在项目中没有找到的接口文档地址。

**Comment by chudongvip** [comment]
哪个端呢？

**Comment by mpasdi** [comment]
web端的

**Comment by chudongvip** [comment]
> web端的
没有的。我们是基于 [RTC SDK](https://docs.anyrtc.io/cn/Video/api-ref/rtc_web/overview) 和 [RTM SDK](https://docs.anyrtc.io/cn/RealTimeMessage/api-ref/rtm_web/overview) 开发的，有能力可以自己去改一下。

- [RTM 查询用户状态](https://docs.anyrtc.io/cn/RealTimeMessage/api-ref/rtm_web/overview#%E6%9F%A5%E8%AF%A2%E7%94%A8%E6%88%B7%E5%9C%A8%E7%BA%BF%E7%8A%B6%E6%80%81)

**Comment by mpasdi** [comment]
ok
